services:
  mysql:
    image: mysql:8.4
    container_name: final_assignment-mysql-1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tms_db
      MYSQL_USER: tms_user
      MYSQL_PASSWORD: tms_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - tms_network

  redis:
    image: redis:7.2-alpine
    container_name: final_assignment-redis-1
    ports:
      - "6379:6379"
    networks:
      - tms_network

  web:
    build: .
    container_name: tms_api
    ports:
      - "5001:5000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=tms_user
      - MYSQL_PASSWORD=tms_password
      - MYSQL_DATABASE=tms_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
    depends_on:
      - mysql
      - redis
    networks:
      - tms_network

volumes:
  mysql_data:

networks:
  tms_network:
    driver: bridge
